### ISSUE TITLE
`--ts` mode should add @embroider/core/types/virtual

### ISSUE THREAD

**Issue by ef4** [mainmatter/ember-vite-codemod#73]
I ran the codemod with `--ts` and ended up with a type error for:

```ts
import compatModules from '@embroider/virtual/compat-modules';
```

I fixed this by editing `types/my-app-name/index.d.ts`:

```diff
+import '@embroider/core/types/virtual';
```

Probably that can go directly into the codemod.

**Comment by Techn1x** [comment]
This worked for me, thanks

**Comment by NullVoxPopuli** [comment]
ye, I think using the tsconfig.json instead is good -- been doing this on most of my projects (and at work), and it's nice to not have a types directory.

```

    "types": ["ember-source/types", "vite/client", "@embroider/core/virtual"]

```

gotta have vite/client as well tho for import.meta.env stuff

**Comment by BlueCutOfficial** [comment]
I finally had time to have a deeper look. I found the file we are missing from the Vite app blueprint, so I'll stick to the blueprint to avoid confusion. I tried to add `@embroider/core/virtual` to the `tsconfig.json`, but it looks like TypeScript needs something more to find the type definition.

**Comment by NullVoxPopuli** [comment]
It's been working for me 🤔 which ts version are you using?

**Comment by BlueCutOfficial** [comment]
I am relying on the app blueprint to create a new app with `--typescript` option, then I run the codemod on it to reproduce the issue. Ember 6.3 gives me `"typescript": "^5.8.2"`, but the idea is to get the codemod to work for all the LTS we support.

**Comment by NullVoxPopuli** [comment]
older versions of typescript don't support package.json#exports, and have bugs with how compilerOptions#types works -- so I could def see older versions of ember needing different tsconfigs -- using older typescript with older ember might be hard :-\ 

the DT Types are community maintained.

_I_ don't support TS on ember projects prior to 4.8 (when the preview types came out, I think)?


tl;dr: you're leading a noble effort, and I don't expect it to be easy. <3

**Comment by BlueCutOfficial** [comment]
Building JavaScript Ember apps with Vite back to 3.28 is already an excellent achievement. If there isn't enough value in bringing TypeScript support that far, I think we can live with it. I fixed the codemod's tests to have a better overview of the TypeScript support, and it deals fine with Ember 5.x. We can also work on prior versions, but it might deserve a dedicated task, which could be a lower priority compared to other open issues.

**Comment by johanrd** [comment]
Editing `types/my-app-name/index.d.ts`did not fix it for me:

```
+import '@embroider/core/types/virtual';
```

I get `Cannot find module '@embroider/virtual/compat-modules' or its corresponding type declarations.ts(2307)` in app.ts. 

Has anything changed lately? Thanks1

"typescript": "^5.8.3",
"@glint/core": "1.4.1-unstable.d17c1f1",
"@embroider/compat": "^4.0.2",
"@embroider/config-meta-loader": "^1.0.0",
"@embroider/core": "^4.0.2",
"@embroider/router": "^3.0.1",
"@embroider/vite": "^1.1.0",

**Comment by Techn1x** [comment]
hey @johanrd I believe it did change - you'll want `@embroider/core/virtual`

Personally I've moved them to tsconfig.json, along with `ember-source/types` and `vite/client`, see NVP's comment above
https://github.com/mainmatter/ember-vite-codemod/issues/73#issuecomment-2784106180

**Comment by johanrd** [comment]
@Techn1x thanks!
